### PR TITLE
added support for uploading a file stream

### PR DESCRIPTION
**Pull request by conor-mac-aoidh**
I needed the option to pass a readable stream to be uploaded to youtube. To do this, I made edits to provide the `Content-Length` and `Content-Type` as arguments.

This is tested and working in my application, but may require further testing.

### CODE REVIEW

**Comment by grayleonard** [comment]
Thanks for the pull request, I know that others want this feature as well. Looks good at first glance, going to take a closer look and test it, will get back to you soon.

**Comment by andela-obogbare** [comment]
Please i am getting the following errors while trying to use this module: 
{ [Function: Error]
  captureStackTrace: [Function: captureStackTrace],
  stackTraceLimit: 10,
  prepareStackTrace: undefined }

**Comment by ghost** [comment]
+1

**Comment by faceyspacey** [comment]
@conor-mac-aoidh is there a reason you always start the upload from scratch by calling `initUpload` rather than `putUpload` (aka `send) like the original used to do? 

Also, I don't suppose you have an idea how to avoid using streams, and plainly use the file to make a request to `self.location`? I'm porting this to React Native where streams aren't supported yet.

**Pull request closed without merging**
